print("Greetings")
import time  
import sys
import os
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("1st time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("2nd time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("3rd time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("4th time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("5th time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("6ht time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("7 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("8 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("9 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("10 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("11 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("12 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("13 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("14 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("15 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("16 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("17 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("18 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("19 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("20 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("21 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("22 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("23 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
print("24 time sleeping")
time.sleep(21600)
print(sys.argv[1])
print(sys.argv[2])
print(os.getenv('lastName'))
print(os.getenv('CDAL_host'))
f= open(os.getenv('MODEL_PATH') + "/model.pl","w+")
f.write("This is demo file")
f.close()
